############################################
# DATABASE CONFIGURATION
############################################

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/oncf_circulation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

############################################
# JPA / HIBERNATE
############################################

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

############################################
# SWAGGER / OPEN API
############################################

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

############################################
# REACT ADMIN
############################################

react-admin-api.host=http://localhost:8080
react-admin-api.use-snake-case=true

############################################
# LOGGING
############################################

logging.level.web=INFO
logging.level.org.springframework.web=INFO
logging.file.name=./logs/oncf-circulation.log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
